{
 "title": "prpd_usb",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "photovoltaic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "energy w",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "prpd_usb_solar_w", "legendFormat": "{{phase}}" }
   ]
  },
  {
   "title": "energy va",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "voltamp" }
   ],
   "targets": [
    { "expr": "prpd_usb_solar_va", "legendFormat": "{{phase}}" }
   ]
  },
  {
   "title": "total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    { "expr": "prpd_usb_solar_total", "legendFormat": "{{phase}}" }
   ]
  },
  { "title": "grid", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "current",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    { "expr": "prpd_usb_grid_current", "legendFormat": "{{phase}}" }
   ]
  },
  {
   "title": "voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "prpd_usb_grid_voltage", "legendFormat": "{{phase}}" }
   ]
  },
  {
   "title": "total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    { "expr": "prpd_usb_grid_total", "legendFormat": "{{phase}}" }
   ]
  },
  {
   "title": "power va",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "voltamp" }
   ],
   "targets": [
    { "expr": "prpd_usb_grid_power_va", "legendFormat": "{{phase}}" }
   ]
  },
  {
   "title": "power w",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "prpd_usb_grid_power_w", "legendFormat": "{{phase}}" }
   ]
  },
  { "title": "platform", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "consumed produced",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    { "expr": "prpd_usb_platform_consumed", "legendFormat": "consumed" },
    { "expr": "prpd_usb_platform_produced", "legendFormat": "produced" }
   ]
  },
  {
   "title": "frequency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    { "expr": "prpd_usb_platform_frequency", "legendFormat": "frequency" }
   ]
  },
  {
   "title": "temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "prpd_usb_platform_temp", "legendFormat": "temperature" }
   ]
  },
  {
   "title": "voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "prpd_usb_platform_voltage", "legendFormat": "voltage" }
   ]
  },
  {
   "title": "power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "prpd_usb_platform_power", "legendFormat": "power" }
   ]
  },
  { "title": "battery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "consumed produced",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "prpd_usb_battery_consumed", "legendFormat": "consumed" },
    { "expr": "prpd_usb_battery_produced", "legendFormat": "produced" }
   ]
  },
  {
   "title": "current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    { "expr": "prpd_usb_battery_current", "legendFormat": "current" }
   ]
  },
  {
   "title": "power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "prpd_usb_battery_power", "legendFormat": "power" }
   ]
  },
  {
   "title": "soc",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "prpd_usb_battery_soc", "legendFormat": "soc" }
   ]
  },
  {
   "title": "voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "prpd_usb_battery_voltage", "legendFormat": "voltage" }
   ]
  },
  {
   "title": "temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 53 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "prpd_usb_battery_temp1", "legendFormat": "temp1" },
    { "expr": "prpd_usb_battery_temp2", "legendFormat": "temp2" }
   ]
  }
 ]
}